# Generated by Django 4.2.13 on 2024-05-31 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=300)),
                ('duration', models.IntegerField(help_text='Duration in seconds')),
                ('description', models.TextField(blank=True)),
                ('video_url', models.FileField(upload_to='uploads')),
                ('workout', models.TextField(max_length=300)),
            ],
            options={
                'db_table': 'exercise',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(max_length=40)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('role', models.CharField(default='user', max_length=30)),
                ('password', models.CharField(default='1234', max_length=255)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.IntegerField(default='0')),
                ('exercise_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weFit.exercise')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weFit.user')),
            ],
            options={
                'db_table': 'user_exercise',
            },
        ),
    ]
