# Generated by Django 4.2.13 on 2024-06-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weFit', '0002_workout_alter_exercise_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='video_url',
            field=models.FileField(upload_to='static/images/gif'),
        ),
    ]
